name: artifact-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd plexity
        cargo build --verbose

    - name: Check formatting of Rust code with rustfmt
      uses: actions-rust-lang/rustfmt@v1.1.0

    - name: Run tests
      run: |
        cd plexity
        cargo test --verbose